id: IA0219D29
legacy_id: null
ocr_import_info:
  bdrc_scan_id: W1KG17112
  source: bdrc
  ocr_info:
    timestamp: '2023-02-01T00:00:00Z'
  batch_id: batch-0002
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2023-12-16T17:01:49.313670'
last_modified: '2023-02-01T00:00:00+00:00'
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG17112
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG17112
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདུལ་འགྲེལ་བློ་གསར་འཇུག་ངོགས་གསེར་གྱི་ཐེམ་སྐས།
  languages:
  - bo
  author: ཕ་ར་དགེ་བཤེས་རྣམ་རྒྱལ་དབང་ཆེན།
statistics: null
quality: null
bases:
  I1KG17122:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17122
      total_pages: 516
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I1KG17122.txt
    order: 1
  I1KG17123:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17123
      total_pages: 510
      volume_number: 2
      volume_pages_bdrc_intro: 2
    base_file: I1KG17123.txt
    order: 2
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
  info_url: null
license: CC0
